import React from 'react';
import * as firebase from 'firebase';
import 'firebase/firestore';
import IconFontAwesome from 'react-native-vector-icons/Ionicons';
import PushController from './PushController';
import PushNotification from 'react-native-push-notification'
import { StyleSheet, Text,FlatList,Alert,View, ScrollView, SafeAreaView,Platform,AppState, TouchableOpacity, TextInput } from 'react-native';
var emailadd=''
firebase.auth().onAuthStateChanged(function(user) {
    if (user) {
        emailadd=user.email;
        
    } else {
      emailadd='';
    }
  });
export default class MedificationSub extends React.Component {

    static navigationOptions = {
        header: null,

    };
    constructor(props) {
        super(props);
        this.handleAppStateChange=this.handleAppStateChange.bind(this);
        this.state={
                    marker:[],
                    arrayOnTouch:[],
                    loading:false,
                    medicationName:'',
                    medicationType:'',
                    medicationDosage:'',
                    medicationQuantity:'',
                    medicationNotes:'',
                }
        this.ref= firebase.firestore().collection('Reminder').where('emailAddress','==',emailadd)
    }


    add = () => {
        //this.props.navigation.navigate('Reminder');
    }
    renderSeparator = () => {  
        return (  
            <View  
                style={{  
                    height: 4,  
                    width: "100%",  
                    backgroundColor: "white",  
                }}  
            />  
        );  
    }; 
    
    //handles the on press of the flatlist
    //shows the details of the medication name pressed
    getListViewItem = (item) => {
        // this.ref= firebase.firestore().collection('Medication').where('medicationName','==',item.medicationName);
        // this.ref.onSnapshot((querySnapshot)=>{
        //     querySnapshot.forEach((doc) => {
        //         this.setState({medicationName:doc.data().medicationName,
        //                         medicationDosage: doc.data().dosage,
        //                         medicationType: doc.data().medicineType,
        //                         medicationNotes: doc.data().medicinenotes,
        //                         medicationQuantity: doc.data().quantity},)
        //         });
        //     });
        //  Alert.alert('The medicine name is: '+JSON.stringify(this.state.medicationName)
        //             +'\nThe medicine type is: '+JSON.stringify(this.state.medicationType)
        //             +'\nThe medicine dosage is: '+JSON.stringify(this.state.medicationDosage)
        //             +'\nThe medicine quanity is: '+JSON.stringify(this.state.medicationQuantity)
        //             +'\nAdditional medicine notes: '+JSON.stringify(this.state.medicationNotes));
        Alert.alert('This flatllist element has been touched.')
    }  

    componentDidMount()
    {
        AppState.addEventListener('change',this.handleAppStateChange);
        this.ref.onSnapshot((querySnapshot)=>{
            const markers = [];
            querySnapshot.forEach((doc) => {
                markers.push({
                    medicationName: doc.data().medicationName,
                    medificationType:doc.data().medicineType,
                    medicationDosage:doc.data().dosage
                });
            });
            this.setState({
                marker: markers,
                loading: false,
            });
        });
    }
    componentWillUnmount()
  {
    AppState.removeEventListener('change',this.handleAppStateChange);
  }
  handleAppStateChange(appState)
  {
    if(appState=='background')
    {
      let date=new Date(Date.now()+(5*1000));
      //todo: Schedule background notification
      if(Platform.OS==='ios')
      {
        date=date.toISOString();
      }
      console.log('app is in background',this.state.seconds);
      PushNotification.localNotificationSchedule({
        id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
    ticker: "My Notification Ticker", // (optional)
    autoCancel: true, // (optional) default: true
    largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
    smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
    bigText: "Check Reminders for any medicine that you need to take", // (optional) default: "message" prop
    subText: "Reminder", // (optional) default: none
    color: "red", // (optional) default: system default
    vibrate: true, // (optional) default: true
    vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
    tag: 'some_tag', // (optional) add tag to message
    group: "group", // (optional) add group to message
    ongoing: false, // (optional) set whether this is an "ongoing" notification
    priority: "high", // (optional) set notification priority, default: high
    visibility: "public", // (optional) set notification visibility, default: private
    importance: "high", // (optional) set notification importance, default: high
    //repeatType: 'minute',
    message:'this is a message',
          date
      });
    }
  }
    render() {
        return (
           <SafeAreaView>
             
                    <View style={styles.container}>
                        <TouchableOpacity style={styles.button}  onPress={this.add}
                       >
                           <IconFontAwesome style={[{ color:'#00806b' }]} size={22} name={'md-add-circle-outline'}/>
                        <Text style={styles.buttonText} > Add Reminder</Text>
                    </TouchableOpacity>
                    </View>
                      <ScrollView>
                    <FlatList  
                    data={this.state.marker}
                    renderItem={({item}) =>  
                    <TouchableOpacity   onPress={this.getListViewItem.bind(this, item)}>
                        <View style={styles.flatlist} >
                              <IconFontAwesome style={[{ color:'#00806b' }]} size={22} name={'md-alarm'} />
                        <Text  style={styles.flatlisttext}
                            >  {item.medicationName}</Text>
                              </View>
                              </TouchableOpacity>}  
                    ItemSeparatorComponent={this.renderSeparator}  
                /> 
                {!!this.state.error && (
                <Text>
                Error message: {this.state.error}
                </Text>
                )}
                
                </ScrollView>
            </SafeAreaView>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        flexDirection:'row',
        justifyContent: 'center',
        alignItems: 'center',
         paddingTop:30,
        paddingBottom:25
    },
    buttonText: {
        fontSize: 22,
        fontWeight: '500',
        color: '#00806b',
        textAlign: 'center', justifyContent: 'center',
        alignItems: 'center',
    },
    button: {
        flex: 1, flexDirection: 'row',
        width: 300,
        backgroundColor: 'white',
        borderRadius: 15,
        marginVertical: 14,
        paddingVertical: 13,
        alignItems: 'center',
        justifyContent: 'center',
       
    },
    flatlist: {  
        flexDirection:'row',
        padding: 10,  
        fontSize: 18,  
        height: 44,  
        backgroundColor:'#e8eaf6',
        color:   '#00806b',
    },  
    flatlisttext:{
         fontSize: 18,  
        height: 44,  
        color:   '#00806b',

    }
});
